# Generated by Django 4.1.1 on 2022-12-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookticket', models.IntegerField(default='max 5 tickets for each booking', max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket_booking',
            name='timestamp',
        ),
    ]
